In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('datasets/RawData.csv')

In [3]:
data

,ClientID,CycleNumber,Group,CycleWithPeakorNot,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofLutealPhase,FirstDayofHigh,...,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
0,nfp8122,1,0,1,0,29,27.33,17,12,12,...,9,,,2,7,7,1,1,0,21.254724111867
1,nfp8122,2,0,1,0,27,,15,12,13,...,,,,,,,,,,
2,nfp8122,3,0,1,0,29,,15,14,,...,,,,,,,,,,
3,nfp8122,4,0,1,0,27,,15,12,13,...,,,,,,,,,,
4,nfp8122,5,0,1,0,28,,16,12,12,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1660,nfp8334,7,1,1,0,29,,19,10,13,...,,,,,,,,,,
1661,nfp8334,8,1,1,0,28,,17,11,12,...,,,,,,,,,,
1662,nfp8334,9,1,1,0,28,,16,12,11,...,,,,,,,,,,
1663,nfp8334,10,1,1,1,40,,27,13,13,...,,,,,,,,,,
1664,nfp8334,11,1,1,2,24,,,,,...,,,,,,,,,,

In [4]:
len(data["ClientID"].unique())

159

In [5]:
# Find the duplicate occurrences of ClientID and CycleNumber
duplicate_occurrences = data[data.duplicated(['ClientID', 'CycleNumber'], keep=False)]

# Group the duplicate occurrences by ClientID and CycleNumber and count the occurrences
duplicate_counts = duplicate_occurrences.groupby(['ClientID', 'CycleNumber']).size().reset_index(name='OccurrenceCount')

# Filter the duplicate counts to keep the occurrences with count greater than 1
duplicate_counts = duplicate_counts[duplicate_counts['OccurrenceCount'] > 1]

# Print the duplicate occurrences
if duplicate_counts.empty:
    print("No occurrences with multiple rows found.")
else:
    print("Occurrences with multiple rows:")
    print(duplicate_counts)

Occurrences with multiple rows:
   ClientID  CycleNumber  OccurrenceCount
0   nfp8106            1                2
1   nfp8106            2                2
2   nfp8106            3                2
3   nfp8107            1                2
4   nfp8107            2                2
5   nfp8107            3                2
6   nfp8107            4                2
7   nfp8107            5                2
8   nfp8107            6                2
9   nfp8107            7                2
10  nfp8107            8                2
11  nfp8109            1                2
12  nfp8109            2                2
13  nfp8109            3                2
14  nfp8114            1                2
15  nfp8114            2                2

In [6]:
to_remove_list = [x for x in duplicate_counts["ClientID"].unique() if x !='nfp8107']
to_remove_list

['nfp8106', 'nfp8109', 'nfp8114']

In [7]:
len(data)

1665

In [8]:
data = data[~data["ClientID"].isin(to_remove_list)]
data.reset_index(drop=True, inplace=True)

In [9]:
data

,ClientID,CycleNumber,Group,CycleWithPeakorNot,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofLutealPhase,FirstDayofHigh,...,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
0,nfp8122,1,0,1,0,29,27.33,17,12,12,...,9,,,2,7,7,1,1,0,21.254724111867
1,nfp8122,2,0,1,0,27,,15,12,13,...,,,,,,,,,,
2,nfp8122,3,0,1,0,29,,15,14,,...,,,,,,,,,,
3,nfp8122,4,0,1,0,27,,15,12,13,...,,,,,,,,,,
4,nfp8122,5,0,1,0,28,,16,12,12,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1644,nfp8334,7,1,1,0,29,,19,10,13,...,,,,,,,,,,
1645,nfp8334,8,1,1,0,28,,17,11,12,...,,,,,,,,,,
1646,nfp8334,9,1,1,0,28,,16,12,11,...,,,,,,,,,,
1647,nfp8334,10,1,1,1,40,,27,13,13,...,,,,,,,,,,
1648,nfp8334,11,1,1,2,24,,,,,...,,,,,,,,,,

In [10]:
filtered_df = data.groupby('ClientID').filter(lambda x: len(x) > 4)
filtered_df.reset_index(drop=True, inplace=True)

In [11]:
filtered_df

,ClientID,CycleNumber,Group,CycleWithPeakorNot,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofLutealPhase,FirstDayofHigh,...,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
0,nfp8122,1,0,1,0,29,27.33,17,12,12,...,9,,,2,7,7,1,1,0,21.254724111867
1,nfp8122,2,0,1,0,27,,15,12,13,...,,,,,,,,,,
2,nfp8122,3,0,1,0,29,,15,14,,...,,,,,,,,,,
3,nfp8122,4,0,1,0,27,,15,12,13,...,,,,,,,,,,
4,nfp8122,5,0,1,0,28,,16,12,12,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1557,nfp8334,7,1,1,0,29,,19,10,13,...,,,,,,,,,,
1558,nfp8334,8,1,1,0,28,,17,11,12,...,,,,,,,,,,
1559,nfp8334,9,1,1,0,28,,16,12,11,...,,,,,,,,,,
1560,nfp8334,10,1,1,1,40,,27,13,13,...,,,,,,,,,,
1561,nfp8334,11,1,1,2,24,,,,,...,,,,,,,,,,

In [12]:
len(filtered_df['ClientID'].unique())

118

In [13]:
filtered_df[filtered_df["ClientID"]=="nfp8107"]

,ClientID,CycleNumber,Group,CycleWithPeakorNot,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofLutealPhase,FirstDayofHigh,...,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
45,nfp8107,1,0,1,0,28,26.88,18,10,,...,7,,,2,3,3,1,1,0,
46,nfp8107,2,0,1,0,27,,18,10,15,...,,,,,,,,,,
47,nfp8107,3,0,1,0,25,,16,9,10,...,,,,,,,,,,
48,nfp8107,4,0,1,0,25,,17,8,12,...,,,,,,,,,,
49,nfp8107,5,0,0,0,29,,,,,...,,,,,,,,,,
50,nfp8107,6,0,0,0,29,,,,17,...,,,,,,,,,,
51,nfp8107,7,0,1,0,28,,19,9,,...,,,,,,,,,,
52,nfp8107,8,0,0,0,24,,,,,...,,,,,,,,,,
470,nfp8107,1,0,1,0,28,26.75,18,10,,...,7,,,2,3,3,1,1,0,
471,nfp8107,2,0,1,0,26,,18,8,15,...,,,,,,,,,,
472,nfp8107,3,0,1,0,25,,16,9,10,...,,,,,,,,,,
473,nfp8107,4,0,1,0,25,,17,8,12,...,,,,,,,,,,
474,nfp8107,5,0,0,0,29,,,,,...,,,,,,,,,,
475,nfp8107,6,0,0,0,29,,,,17,...,,,,,,,,,,
476,nfp8107,7,0,1,0,28,,19,9,,...,,,,,,,,,,
477,nfp8107,8,0,0,0,24,,,,,...,,,,,,,,,,

In [14]:
# filtered_df.drop(filtered_df.index[470:478], inplace=True)
filtered_df.drop(filtered_df.index[45:53], inplace=True)
filtered_df.reset_index(drop=True, inplace=True)

In [15]:
filtered_df[filtered_df["ClientID"]=="nfp8107"]

,ClientID,CycleNumber,Group,CycleWithPeakorNot,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofLutealPhase,FirstDayofHigh,...,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
462,nfp8107,1,0,1,0,28,26.75,18,10,,...,7,,,2,3,3,1,1,0,
463,nfp8107,2,0,1,0,26,,18,8,15,...,,,,,,,,,,
464,nfp8107,3,0,1,0,25,,16,9,10,...,,,,,,,,,,
465,nfp8107,4,0,1,0,25,,17,8,12,...,,,,,,,,,,
466,nfp8107,5,0,0,0,29,,,,,...,,,,,,,,,,
467,nfp8107,6,0,0,0,29,,,,17,...,,,,,,,,,,
468,nfp8107,7,0,1,0,28,,19,9,,...,,,,,,,,,,
469,nfp8107,8,0,0,0,24,,,,,...,,,,,,,,,,

In [16]:
filtered_df

,ClientID,CycleNumber,Group,CycleWithPeakorNot,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofLutealPhase,FirstDayofHigh,...,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
0,nfp8122,1,0,1,0,29,27.33,17,12,12,...,9,,,2,7,7,1,1,0,21.254724111867
1,nfp8122,2,0,1,0,27,,15,12,13,...,,,,,,,,,,
2,nfp8122,3,0,1,0,29,,15,14,,...,,,,,,,,,,
3,nfp8122,4,0,1,0,27,,15,12,13,...,,,,,,,,,,
4,nfp8122,5,0,1,0,28,,16,12,12,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1549,nfp8334,7,1,1,0,29,,19,10,13,...,,,,,,,,,,
1550,nfp8334,8,1,1,0,28,,17,11,12,...,,,,,,,,,,
1551,nfp8334,9,1,1,0,28,,16,12,11,...,,,,,,,,,,
1552,nfp8334,10,1,1,1,40,,27,13,13,...,,,,,,,,,,
1553,nfp8334,11,1,1,2,24,,,,,...,,,,,,,,,,

In [17]:
filtered_df.to_csv('datasets/FilteredData.csv', index=False)

In [18]:
filtered_df.set_index('ClientID').T["nfp8107"]

ClientID,nfp8107,nfp8107,nfp8107,nfp8107,nfp8107,nfp8107,nfp8107,nfp8107
CycleNumber,1,2,3,4,5,6,7,8
Group,0,0,0,0,0,0,0,0
CycleWithPeakorNot,1,1,1,1,0,0,1,0
ReproductiveCategory,0,0,0,0,0,0,0,0
LengthofCycle,28,26,25,25,29,29,28,24
...,...,...,...,...,...,...,...,...
NextpregM,3,,,,,,,
Spousesame,1,,,,,,,
SpousesameM,1,,,,,,,
Timeattemptpreg,0,,,,,,,
BMI,,,,,,,,